# Description
# ===========
# This playbook updates image reference in Virtual Machine Scaleset.
# This sample requires Ansible 2.8
---
- name: Update VMSS Image Referece
  hosts: localhost
  connection: local
  tasks:

  - name: Update VMSS with image
    azure_rm_virtualmachinescaleset:
      resource_group: "{{ deployment_resource_group_name }}"
      name: "{{ vmss_name }}"
      admin_username: "{{ admin_default_username }}"
      admin_password: "{{ admin_default_password }}"
      capacity: "{{ capacity }}"
      upgrade_policy: Manual
      platform_fault_domain_count: 5
      image:
        name: "{{ image_name }}"
        resource_group: "{{ vmimage_resource_group }}"

  - name: List all of the instances
    azure_rm_virtualmachinescalesetinstance_info:
      resource_group: "{{ deployment_resource_group_name }}"
      vmss_name: "{{ vmss_name }}"
    register: instances

  - debug:
      var: instances

  - name: manually upgrade all the instances 
    azure_rm_virtualmachinescalesetinstance:
      resource_group: "{{ resource_group }}"
      vmss_name: "{{ vmss_name }}"
      instance_id: "{{ item.instance_id }}"
      latest_model: yes
    with_items: "{{ instances.instances }}"
